### ISSUE TITLE
bug(admin/attendance): filter no longer working

### ISSUE THREAD

**Issue by QiLinXue** [volunteeringpeel/volunteeringpeel#104]
The "Assigned to me" and "Unconfirmed" filter on the attendance page no longer works.

**Comment by RetroCraft** [comment]
Bug appears to be related to this line where the sorted data is overwriting the filtered data. Will push out fix soon after running some tests + documentation (since this whole codebase is sorely lacking in documentation)
https://github.com/volunteeringpeel/volunteeringpeel/blob/153feab82d640bf5777f5e2cfecd4b7894f19597/src/app/common/components/FancyTable.tsx#L141
